export interface Industry {
  slug: string
  name: string
  tagline: string
  description: string
  icon: string
  color: string
  bgColor: string
  challenges: string[]
  solutions: { title: string; desc: string }[]
  outcomes: { metric: string; label: string }[]
  useCases: string[]
  comingSoon?: boolean
}

export const industries: Industry[] = [
  {
    slug: 'healthcare',
    name: 'Healthcare',
    icon: '🏥',
    color: 'text-red-600',
    bgColor: 'bg-red-50',
    tagline: 'AI that saves time, improves outcomes, and transforms patient care.',
    description: 'From medical imaging to clinical decision support, we build AI solutions that help healthcare organisations deliver better patient outcomes, reduce administrative burden, and operate more efficiently.',
    challenges: [
      'Manual and time-consuming diagnostics workflows',
      'Overwhelming volumes of unstructured clinical data',
      'High administrative burden on clinical staff',
      'Difficulty predicting patient risk and readmission',
    ],
    solutions: [
      { title: 'Medical Imaging AI', desc: 'Computer vision models for radiology, pathology, and diagnostic imaging with clinical-grade accuracy.' },
      { title: 'Clinical NLP', desc: 'Extract insights from clinical notes, discharge summaries, and medical records automatically.' },
      { title: 'Predictive Risk Models', desc: 'Identify high-risk patients, predict readmissions, and optimise care pathways.' },
      { title: 'AI-Powered Administration', desc: 'Automate scheduling, billing, coding, and compliance workflows.' },
    ],
    outcomes: [
      { metric: '94%', label: 'Diagnostic accuracy' },
      { metric: '40%', label: 'Admin time saved' },
      { metric: '30%', label: 'Cost reduction' },
      { metric: '25%', label: 'Faster diagnoses' },
    ],
    useCases: ['Medical imaging analysis', 'Patient risk stratification', 'Clinical documentation AI', 'Drug discovery support', 'Appointment scheduling automation', 'Claims processing AI'],
  },
  {
    slug: 'finance',
    name: 'Finance & Banking',
    icon: '🏦',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50',
    tagline: 'Intelligent finance — faster decisions, lower risk, better customer experiences.',
    description: 'We help banks, fintechs, and investment firms harness AI for fraud detection, risk modelling, trading intelligence, and hyper-personalised customer experiences.',
    challenges: [
      'Real-time fraud detection at scale',
      'Manual credit risk assessment processes',
      'Regulatory compliance and reporting burden',
      'Fragmented customer data limiting personalisation',
    ],
    solutions: [
      { title: 'Fraud Detection AI', desc: 'Real-time transaction monitoring with ML models that detect anomalies and reduce false positives.' },
      { title: 'Credit Risk Modelling', desc: 'AI-powered credit scoring and risk assessment for faster, more accurate lending decisions.' },
      { title: 'Trading Intelligence', desc: 'Real-time data pipelines and predictive models for portfolio management and algorithmic trading.' },
      { title: 'Regulatory AI', desc: 'Automated compliance monitoring, AML detection, and regulatory reporting.' },
    ],
    outcomes: [
      { metric: '60%', label: 'Fraud reduction' },
      { metric: '3x', label: 'Faster risk decisions' },
      { metric: '45%', label: 'Compliance cost savings' },
      { metric: '35%', label: 'Revenue uplift' },
    ],
    useCases: ['Fraud & AML detection', 'Algorithmic trading', 'Credit scoring', 'KYC automation', 'Customer churn prediction', 'Regulatory reporting'],
  },
  {
    slug: 'retail',
    name: 'Retail & E-commerce',
    icon: '🛍️',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50',
    tagline: 'AI-powered retail — personalised, efficient, and data-driven at every touchpoint.',
    description: 'From recommendation engines to demand forecasting, we help retailers and e-commerce companies use AI to increase sales, optimise inventory, and deliver exceptional customer experiences.',
    challenges: [
      'Low personalisation leading to poor conversion rates',
      'Inventory inefficiencies and stockout/overstock issues',
      'Rising customer service costs',
      'Fragmented omnichannel experience',
    ],
    solutions: [
      { title: 'AI Recommendation Engine', desc: 'Personalised product recommendations that increase basket size and customer lifetime value.' },
      { title: 'Demand Forecasting', desc: 'ML models that predict demand patterns and optimise inventory levels across channels.' },
      { title: 'AI Customer Support', desc: 'LLM-powered support agents that resolve 70%+ of queries without human intervention.' },
      { title: 'Visual Search & Commerce', desc: 'Computer vision for visual product search, virtual try-on, and automated cataloguing.' },
    ],
    outcomes: [
      { metric: '30%', label: 'Sales increase' },
      { metric: '72%', label: 'Support automation' },
      { metric: '25%', label: 'Inventory reduction' },
      { metric: '40%', label: 'Customer satisfaction' },
    ],
    useCases: ['Product recommendations', 'Demand forecasting', 'AI chatbot support', 'Price optimisation', 'Visual search', 'Churn prediction'],
  },
  {
    slug: 'manufacturing',
    name: 'Manufacturing',
    icon: '🏭',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50',
    tagline: 'Smart manufacturing — AI-powered efficiency, quality, and uptime.',
    description: 'We help manufacturers reduce downtime, improve quality, optimise supply chains, and build intelligent factory operations through AI and IoT integration.',
    challenges: [
      'Unplanned equipment downtime and maintenance costs',
      'Manual quality inspection bottlenecks',
      'Supply chain disruptions and inefficiencies',
      'Energy waste and rising operational costs',
    ],
    solutions: [
      { title: 'Predictive Maintenance', desc: 'IoT + ML systems that predict equipment failures before they happen, reducing downtime by 38%+.' },
      { title: 'AI Quality Inspection', desc: 'Computer vision for automated defect detection at line speed with human-level accuracy.' },
      { title: 'Supply Chain AI', desc: 'Demand sensing, supplier risk monitoring, and logistics optimisation powered by AI.' },
      { title: 'Energy Optimisation', desc: 'ML models that reduce energy consumption by identifying waste patterns in real time.' },
    ],
    outcomes: [
      { metric: '38%', label: 'Downtime reduction' },
      { metric: '45%', label: 'Defect detection rate' },
      { metric: '20%', label: 'Energy savings' },
      { metric: '3x', label: 'Quality throughput' },
    ],
    useCases: ['Predictive maintenance', 'Visual quality inspection', 'Supply chain optimisation', 'Energy management', 'Production scheduling AI', 'Worker safety AI'],
  },
  {
    slug: 'logistics',
    name: 'Logistics',
    icon: '🚚',
    color: 'text-teal-600',
    bgColor: 'bg-teal-50',
    tagline: 'Smarter logistics — optimised routes, automated operations, real-time visibility.',
    description: 'We help logistics and supply chain companies reduce costs, improve delivery performance, and build real-time operational intelligence through AI and automation.',
    challenges: [
      'Inefficient route planning driving up fuel costs',
      'Manual warehouse operations slowing fulfilment',
      'Limited real-time visibility across the supply chain',
      'High last-mile delivery costs and failures',
    ],
    solutions: [
      { title: 'Route Optimisation AI', desc: 'Dynamic route planning that reduces fuel costs and improves on-time delivery rates.' },
      { title: 'Warehouse Automation', desc: 'AI-powered picking, sorting, and inventory management for faster fulfilment.' },
      { title: 'Supply Chain Visibility', desc: 'Real-time tracking and predictive analytics across the full supply chain.' },
      { title: 'Demand Sensing', desc: 'ML forecasting for shipment volumes enabling better capacity planning.' },
    ],
    outcomes: [
      { metric: '45%', label: 'Operational cost saving' },
      { metric: '30%', label: 'Delivery time reduction' },
      { metric: '25%', label: 'Fuel cost savings' },
      { metric: '99%', label: 'Tracking accuracy' },
    ],
    useCases: ['Route optimisation', 'Fleet management AI', 'Warehouse robotics', 'Demand forecasting', 'Last-mile AI', 'Supply chain risk monitoring'],
  },
  {
    slug: 'education',
    name: 'Education',
    icon: '🎓',
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
    tagline: 'AI-powered learning — personalised, accessible, and outcome-focused.',
    description: 'We help educational institutions and EdTech companies use AI to personalise learning, identify at-risk students, automate administration, and deliver better outcomes at scale.',
    challenges: [
      'One-size-fits-all learning not meeting individual needs',
      'Identifying at-risk students before they disengage',
      'High administrative burden on educators',
      'Scaling quality education to larger student populations',
    ],
    solutions: [
      { title: 'Adaptive Learning AI', desc: 'Personalised learning paths that adapt to each student\'s pace, style, and performance.' },
      { title: 'Student Analytics', desc: 'Early warning systems that identify at-risk students and trigger timely interventions.' },
      { title: 'AI Teaching Assistant', desc: 'LLM-powered assistants that answer student questions, grade assignments, and provide feedback 24/7.' },
      { title: 'Admin Automation', desc: 'Automate enrolment, scheduling, reporting, and compliance workflows.' },
    ],
    outcomes: [
      { metric: '35%', label: 'Improved outcomes' },
      { metric: '50%', label: 'Admin time saved' },
      { metric: '28%', label: 'Dropout reduction' },
      { metric: '40%', label: 'Student satisfaction' },
    ],
    useCases: ['Adaptive learning platforms', 'Student risk prediction', 'AI tutoring', 'Plagiarism detection', 'Automated grading', 'Enrolment AI'],
  },
  {
    slug: 'real-estate',
    name: 'Real Estate',
    icon: '🏢',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50',
    tagline: 'AI-driven property intelligence — smarter valuations, faster deals, better tenant experiences.',
    description: 'From automated property valuations to AI-powered tenant screening, we help real estate companies make faster, data-driven decisions across the full property lifecycle.',
    challenges: ['Manual property valuation processes', 'High tenant acquisition and screening costs', 'Fragmented property management data', 'Slow deal pipeline and document processing'],
    solutions: [
      { title: 'Automated Valuation Models', desc: 'ML models that estimate property values in real time using location, market, and structural data.' },
      { title: 'AI Tenant Screening', desc: 'Risk-scoring models that accelerate tenant qualification while reducing bias and compliance risk.' },
      { title: 'Portfolio Analytics', desc: 'Dashboards that give portfolio managers a real-time view of occupancy, yield, and risk exposure.' },
      { title: 'Document AI', desc: 'Automated lease extraction, contract review, and compliance checks.' },
    ],
    outcomes: [
      { metric: '60%', label: 'Faster valuations' },
      { metric: '40%', label: 'Screening time saved' },
      { metric: '25%', label: 'Portfolio yield improvement' },
      { metric: '80%', label: 'Document processing automation' },
    ],
    useCases: ['Property valuation AI', 'Tenant screening', 'Lease document extraction', 'Market forecasting', 'Portfolio optimisation', 'Maintenance prediction'],
    comingSoon: true,
  },
  {
    slug: 'government',
    name: 'Government',
    icon: '🏛️',
    color: 'text-slate-600',
    bgColor: 'bg-slate-100',
    tagline: 'AI for public services — efficient, transparent, and citizen-centric.',
    description: 'We help government agencies automate high-volume manual processes, improve service delivery, and build AI systems that are transparent, auditable, and compliant with public sector requirements.',
    challenges: ['High-volume manual document processing', 'Fragmented citizen data across agencies', 'Long service delivery timelines', 'Regulatory and auditability requirements for AI'],
    solutions: [
      { title: 'Document & Forms AI', desc: 'Automated extraction and processing of government forms, applications, and compliance documents.' },
      { title: 'Case Management AI', desc: 'Intelligent routing, prioritisation, and decision-support for case officers.' },
      { title: 'Citizen Service Chatbots', desc: 'LLM-powered assistants that resolve citizen queries 24/7, reducing call centre load.' },
      { title: 'Fraud & Benefits Analytics', desc: 'Anomaly detection models that identify fraudulent claims and benefit errors at scale.' },
    ],
    outcomes: [
      { metric: '60%', label: 'Faster processing' },
      { metric: '45%', label: 'Staff time saved' },
      { metric: '70%', label: 'Query automation' },
      { metric: '35%', label: 'Error rate reduction' },
    ],
    useCases: ['Document processing AI', 'Benefits fraud detection', 'Citizen chatbots', 'RPA automation', 'Policy compliance monitoring', 'Procurement analytics'],
    comingSoon: true,
  },
  {
    slug: 'pharma',
    name: 'Pharma & Life Sciences',
    icon: '🔬',
    color: 'text-violet-600',
    bgColor: 'bg-violet-50',
    tagline: 'Accelerating discovery, trials, and compliance with AI.',
    description: 'From drug discovery to pharmacovigilance, we build AI systems that help pharma and life sciences organisations move faster, reduce costs, and maintain strict regulatory compliance.',
    challenges: ['Long and expensive drug discovery cycles', 'Manual adverse event monitoring and reporting', 'Clinical trial inefficiencies and recruitment failures', 'Complex regulatory submission requirements'],
    solutions: [
      { title: 'Drug Discovery AI', desc: 'Generative models and molecular screening pipelines that accelerate lead compound identification.' },
      { title: 'Pharmacovigilance AI', desc: 'NLP systems that monitor adverse event signals across clinical, social, and scientific data.' },
      { title: 'Clinical Trial Optimisation', desc: 'Patient matching, site selection, and dropout prediction to improve trial efficiency.' },
      { title: 'Regulatory Intelligence', desc: 'AI-assisted submission preparation and compliance monitoring across global jurisdictions.' },
    ],
    outcomes: [
      { metric: '40%', label: 'Discovery time reduction' },
      { metric: '3x', label: 'Adverse event detection' },
      { metric: '30%', label: 'Trial cost savings' },
      { metric: '50%', label: 'Submission time saved' },
    ],
    useCases: ['Molecular screening', 'Adverse event monitoring', 'Clinical trial matching', 'Drug repurposing AI', 'Regulatory submission AI', 'Real-world evidence analytics'],
    comingSoon: true,
  },
  {
    slug: 'energy',
    name: 'Energy & Utilities',
    icon: '⚡',
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-50',
    tagline: 'Smarter grids, lower emissions, higher efficiency through AI.',
    description: 'We help energy and utilities companies optimise grid operations, predict demand, reduce emissions, and build intelligent asset management systems powered by AI and IoT.',
    challenges: ['Unpredictable renewable energy output', 'Ageing asset infrastructure and unplanned outages', 'Rising operational costs and energy waste', 'Complex regulatory reporting requirements'],
    solutions: [
      { title: 'Demand Forecasting', desc: 'ML models that predict energy demand with high accuracy, enabling better grid balancing and cost savings.' },
      { title: 'Predictive Asset Management', desc: 'IoT + AI systems that predict equipment failures before they occur, reducing outage risk.' },
      { title: 'Renewable Optimisation', desc: 'AI scheduling and dispatch optimisation for solar, wind, and storage assets.' },
      { title: 'Emissions Analytics', desc: 'Real-time carbon tracking and reduction scenario modelling for ESG compliance.' },
    ],
    outcomes: [
      { metric: '25%', label: 'Grid efficiency gain' },
      { metric: '35%', label: 'Outage reduction' },
      { metric: '20%', label: 'Cost savings' },
      { metric: '30%', label: 'Emissions reduction' },
    ],
    useCases: ['Demand forecasting', 'Grid optimisation', 'Asset lifecycle AI', 'Renewable scheduling', 'Carbon emissions tracking', 'Smart meter analytics'],
    comingSoon: true,
  },
  {
    slug: 'telecom',
    name: 'Telecom',
    icon: '📡',
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-50',
    tagline: 'Network intelligence, churn prevention, and customer experience AI for telecoms.',
    description: 'We help telecommunications companies reduce churn, optimise network performance, automate customer operations, and unlock new revenue streams through advanced AI and analytics.',
    challenges: ['High customer churn rates in competitive markets', 'Network performance monitoring at massive scale', 'Rising customer service costs', 'Fraud and revenue assurance risks'],
    solutions: [
      { title: 'Churn Prediction AI', desc: 'ML models that identify at-risk customers and trigger personalised retention interventions.' },
      { title: 'Network Analytics', desc: 'Real-time network performance monitoring with AI-powered anomaly detection and root cause analysis.' },
      { title: 'AI Customer Operations', desc: 'LLM-powered virtual agents that handle billing, fault reporting, and plan changes autonomously.' },
      { title: 'Fraud Detection', desc: 'Real-time fraud scoring for subscription fraud, SIM swapping, and interconnect billing anomalies.' },
    ],
    outcomes: [
      { metric: '30%', label: 'Churn reduction' },
      { metric: '50%', label: 'Support automation' },
      { metric: '40%', label: 'Fraud loss reduction' },
      { metric: '25%', label: 'Network OPEX savings' },
    ],
    useCases: ['Churn prediction', 'Network fault detection', 'AI billing support', 'Fraud scoring', 'Personalised plan recommendations', 'Capacity planning AI'],
    comingSoon: true,
  },
  {
    slug: 'agriculture',
    name: 'Agriculture',
    icon: '🌾',
    color: 'text-lime-600',
    bgColor: 'bg-lime-50',
    tagline: 'Precision agriculture — AI for smarter yields, less waste, and sustainable farming.',
    description: 'We help agricultural businesses increase crop yields, reduce input costs, optimise supply chains, and build sustainable farming practices through AI, IoT, and remote sensing technologies.',
    challenges: ['Unpredictable weather and crop yield variability', 'High input costs and inefficient resource usage', 'Pest and disease detection delays', 'Post-harvest waste and supply chain inefficiencies'],
    solutions: [
      { title: 'Crop Yield Prediction', desc: 'ML models combining satellite imagery, weather data, and soil sensors to forecast yields accurately.' },
      { title: 'Precision Irrigation AI', desc: 'IoT + AI systems that optimise water usage based on real-time field conditions.' },
      { title: 'Disease & Pest Detection', desc: 'Computer vision models that identify crop diseases and pest infestations from drone imagery.' },
      { title: 'Supply Chain Intelligence', desc: 'Demand sensing and logistics optimisation to reduce post-harvest losses.' },
    ],
    outcomes: [
      { metric: '25%', label: 'Yield improvement' },
      { metric: '30%', label: 'Water usage reduction' },
      { metric: '45%', label: 'Earlier disease detection' },
      { metric: '20%', label: 'Post-harvest loss reduction' },
    ],
    useCases: ['Crop yield prediction', 'Precision irrigation', 'Disease detection AI', 'Drone image analysis', 'Supply chain optimisation', 'Soil health monitoring'],
    comingSoon: true,
  },
  {
    slug: 'legal',
    name: 'Legal & Compliance',
    icon: '⚖️',
    color: 'text-stone-600',
    bgColor: 'bg-stone-100',
    tagline: 'AI for legal — faster due diligence, smarter contract review, lower compliance risk.',
    description: 'We help law firms, in-house legal teams, and compliance departments automate document-heavy workflows, reduce review time, and manage regulatory risk with AI-powered legal technology.',
    challenges: ['Time-consuming contract review and due diligence', 'Keeping pace with changing regulatory requirements', 'Manual e-discovery and document review processes', 'Knowledge management across large legal teams'],
    solutions: [
      { title: 'Contract Intelligence', desc: 'AI that extracts, classifies, and flags risk clauses across thousands of contracts in hours, not weeks.' },
      { title: 'Regulatory Monitoring', desc: 'Automated tracking of regulatory changes relevant to your jurisdiction and business activities.' },
      { title: 'Legal Research AI', desc: 'LLM-powered research assistants that surface relevant case law and precedents rapidly.' },
      { title: 'E-Discovery Automation', desc: 'ML-driven document classification and privilege review to reduce e-discovery costs significantly.' },
    ],
    outcomes: [
      { metric: '70%', label: 'Contract review time saved' },
      { metric: '60%', label: 'e-Discovery cost reduction' },
      { metric: '80%', label: 'Compliance monitoring automation' },
      { metric: '3x', label: 'Research speed improvement' },
    ],
    useCases: ['Contract review AI', 'Regulatory change monitoring', 'Legal research assistant', 'E-discovery automation', 'Risk clause extraction', 'Compliance reporting'],
    comingSoon: true,
  },
  {
    slug: 'media',
    name: 'Media & Entertainment',
    icon: '🎬',
    color: 'text-pink-600',
    bgColor: 'bg-pink-50',
    tagline: 'Content intelligence, personalisation, and production AI for media companies.',
    description: 'We help media and entertainment companies use AI to personalise content experiences, automate production workflows, protect against piracy, and unlock audience insights at scale.',
    challenges: ['Content discovery and personalisation at scale', 'High production and localisation costs', 'Digital piracy and rights management', 'Fragmented audience data across platforms'],
    solutions: [
      { title: 'Content Recommendation Engine', desc: 'Deep learning recommendation systems that increase engagement and reduce churn for streaming platforms.' },
      { title: 'Automated Content Production', desc: 'AI tools for subtitle generation, dubbing, content tagging, and metadata enrichment at scale.' },
      { title: 'Audience Intelligence', desc: 'Unified audience analytics that combine first-party and behavioural data for better targeting and commissioning.' },
      { title: 'Piracy Detection AI', desc: 'Computer vision and fingerprinting models that detect unauthorised content distribution in near real time.' },
    ],
    outcomes: [
      { metric: '35%', label: 'Engagement increase' },
      { metric: '50%', label: 'Production cost savings' },
      { metric: '40%', label: 'Piracy detection rate' },
      { metric: '25%', label: 'Subscriber retention lift' },
    ],
    useCases: ['Content recommendation', 'Auto subtitling & dubbing', 'Audience segmentation', 'Piracy fingerprinting', 'Content moderation AI', 'Commissioning analytics'],
    comingSoon: true,
  },
  {
    slug: 'insurance',
    name: 'Insurance',
    icon: '🛡️',
    color: 'text-blue-700',
    bgColor: 'bg-blue-50',
    tagline: 'Smarter underwriting, faster claims, and lower fraud — powered by AI.',
    description: 'We help insurers modernise underwriting, accelerate claims processing, detect fraud in real time, and deliver personalised customer experiences through advanced AI and data analytics.',
    challenges: ['Manual and slow claims processing', 'Inaccurate risk assessment and pricing', 'High fraudulent claims volumes', 'Poor customer retention and acquisition costs'],
    solutions: [
      { title: 'Intelligent Claims Processing', desc: 'AI systems that automate straight-through processing for low-complexity claims, reducing settlement time from weeks to hours.' },
      { title: 'AI Underwriting', desc: 'ML models that improve risk assessment accuracy and automate routine underwriting decisions.' },
      { title: 'Claims Fraud Detection', desc: 'Graph analytics and anomaly detection that identify fraudulent claims patterns at submission.' },
      { title: 'Customer Lifetime Value AI', desc: 'Predictive models that identify at-risk policyholders and optimise renewal and cross-sell strategies.' },
    ],
    outcomes: [
      { metric: '70%', label: 'Claims processing time saved' },
      { metric: '45%', label: 'Fraud detection improvement' },
      { metric: '30%', label: 'Underwriting cost reduction' },
      { metric: '25%', label: 'Customer retention lift' },
    ],
    useCases: ['Claims automation', 'Fraud detection', 'AI underwriting', 'Telematics scoring', 'Customer churn prediction', 'Document extraction'],
    comingSoon: true,
  },
  {
    slug: 'travel',
    name: 'Travel & Hospitality',
    icon: '✈️',
    color: 'text-sky-600',
    bgColor: 'bg-sky-50',
    tagline: 'AI for travel — personalised experiences, dynamic pricing, and operational intelligence.',
    description: 'We help travel and hospitality companies increase bookings, optimise pricing, reduce cancellations, and deliver personalised guest experiences through AI and predictive analytics.',
    challenges: ['Low booking conversion and high abandonment rates', 'Inefficient and static pricing strategies', 'High operational costs and manual service workflows', 'Rising customer expectations for personalisation'],
    solutions: [
      { title: 'Dynamic Pricing AI', desc: 'Real-time pricing optimisation that responds to demand signals, competitor rates, and booking velocity.' },
      { title: 'Personalisation Engine', desc: 'AI-driven recommendations for hotels, flights, activities, and upgrades that increase average order value.' },
      { title: 'Demand Forecasting', desc: 'Accurate occupancy and booking demand forecasts that improve staffing and inventory decisions.' },
      { title: 'AI Guest Services', desc: 'Conversational AI for booking support, concierge, and post-stay engagement.' },
    ],
    outcomes: [
      { metric: '20%', label: 'Revenue per available room' },
      { metric: '35%', label: 'Conversion rate lift' },
      { metric: '30%', label: 'Support cost reduction' },
      { metric: '25%', label: 'Customer satisfaction gain' },
    ],
    useCases: ['Dynamic pricing', 'Demand forecasting', 'AI concierge', 'Personalised offers', 'Cancellation prediction', 'Review sentiment AI'],
    comingSoon: true,
  },
]

export function getIndustry(slug: string): Industry | undefined {
  return industries.find(i => i.slug === slug)
}
